// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/atleta": {
            "post": {
                "description": "Cadastra um novo atleta no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Atletas"
                ],
                "summary": "Cria um novo atleta",
                "parameters": [
                    {
                        "description": "Dados do atleta",
                        "name": "atleta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    },
                    "400": {
                        "description": "Falha ao cadastrar atleta",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    }
                }
            }
        },
        "/atleta/{cpf}": {
            "get": {
                "description": "Busca um atleta pelo CPF informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Atletas"
                ],
                "summary": "Exibe um atleta por CPF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do atleta",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    },
                    "404": {
                        "description": "Atleta não encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    }
                }
            },
            "patch": {
                "description": "Atualiza os dados de um atleta existente pelo CPF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Atletas"
                ],
                "summary": "Atualiza um atleta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do atleta",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do atleta",
                        "name": "atleta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos para atualização",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    },
                    "404": {
                        "description": "Atleta não encontrado",
                        "schema": {
                            "$ref": "#/definitions/models.Atleta"
                        }
                    }
                }
            }
        },
        "/atletas": {
            "get": {
                "description": "Retorna uma lista de todos os atletas cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Atletas"
                ],
                "summary": "Exibe todos os atletas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Atleta"
                            }
                        }
                    }
                }
            }
        },
        "/equipe": {
            "post": {
                "description": "Cadastra uma nova equipe no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipes"
                ],
                "summary": "Cria uma nova equipe",
                "parameters": [
                    {
                        "description": "Dados da equipe",
                        "name": "equipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    },
                    "400": {
                        "description": "Falha ao cadastrar equipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Falha ao salvar equipe no banco de dados",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/equipe/{id}": {
            "get": {
                "description": "Busca uma equipe pelo ID informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipes"
                ],
                "summary": "Exibe uma equipe por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da equipe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    },
                    "404": {
                        "description": "Equipe não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove uma equipe do sistema pelo ID informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipes"
                ],
                "summary": "Deleta uma equipe por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da equipe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Equipe deletada com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Equipe não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Falha ao deletar a equipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Atualiza os dados de uma equipe existente pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipes"
                ],
                "summary": "Atualiza uma equipe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da equipe",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados da equipe",
                        "name": "equipe",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos para atualização",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Equipe não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Falha ao atualizar a equipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/equipes": {
            "get": {
                "description": "Retorna uma lista de todas as equipes cadastradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Equipes"
                ],
                "summary": "Exibe todas as equipes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Equipe"
                            }
                        }
                    }
                }
            }
        },
        "/lider": {
            "post": {
                "description": "Cadastra um novo líder no sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Líderes"
                ],
                "summary": "Cria um novo líder",
                "parameters": [
                    {
                        "description": "Dados do líder",
                        "name": "lider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Lider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Lider"
                        }
                    },
                    "400": {
                        "description": "Falha ao cadastrar líder",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/lider/{cpf}": {
            "get": {
                "description": "Busca um líder pelo CPF informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Líderes"
                ],
                "summary": "Exibe um líder por CPF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do líder",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Lider"
                        }
                    },
                    "404": {
                        "description": "Líder não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove um líder do sistema pelo CPF informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Líderes"
                ],
                "summary": "Deleta um líder por CPF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do líder",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Líder deletado com sucesso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Líder não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Falha ao deletar o líder",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "patch": {
                "description": "Atualiza os dados de um líder existente pelo CPF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Líderes"
                ],
                "summary": "Atualiza um líder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CPF do líder",
                        "name": "cpf",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados atualizados do líder",
                        "name": "lider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Lider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Lider"
                        }
                    },
                    "400": {
                        "description": "Dados inválidos para atualização",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Líder não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Falha ao atualizar o líder",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/lideres": {
            "get": {
                "description": "Retorna uma lista de todos os líderes cadastrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Líderes"
                ],
                "summary": "Exibe todos os líderes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Lider"
                            }
                        }
                    }
                }
            }
        },
        "/pergunta/{id}": {
            "get": {
                "description": "Busca uma pergunta pelo ID informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perguntas"
                ],
                "summary": "Exibe uma pergunta por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da pergunta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pergunta"
                        }
                    },
                    "404": {
                        "description": "Pergunta não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pergunta/{id}/respostas": {
            "get": {
                "description": "Busca uma pergunta com todas as respostas associadas pelo ID informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perguntas"
                ],
                "summary": "Exibe uma pergunta com suas respostas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da pergunta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Pergunta"
                        }
                    },
                    "404": {
                        "description": "Pergunta não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/perguntas": {
            "get": {
                "description": "Retorna uma lista de todas as perguntas cadastradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perguntas"
                ],
                "summary": "Exibe todas as perguntas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pergunta"
                            }
                        }
                    }
                }
            }
        },
        "/perguntas/respostas": {
            "get": {
                "description": "Busca todas as perguntas com suas respostas associadas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Perguntas"
                ],
                "summary": "Exibe todas as perguntas com suas respostas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Pergunta"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro ao buscar perguntas",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/resposta/{id}": {
            "get": {
                "description": "Busca uma resposta pelo ID informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Respostas"
                ],
                "summary": "Exibe uma resposta por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da resposta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Resposta"
                        }
                    },
                    "404": {
                        "description": "Resposta não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/respostas": {
            "get": {
                "description": "Retorna uma lista de todas as respostas cadastradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Respostas"
                ],
                "summary": "Exibe todas as respostas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Resposta"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Atleta": {
            "description": "Representa um atleta com informações básicas.",
            "type": "object",
            "properties": {
                "ativo": {
                    "description": "Status ativo do atleta",
                    "type": "integer"
                },
                "cpf": {
                    "description": "CPF do atleta",
                    "type": "string"
                },
                "cpf_lider": {
                    "description": "CPF do líder associado",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Data de criação",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Data de exclusão (opcional)",
                    "type": "string"
                },
                "email": {
                    "description": "Email do atleta",
                    "type": "string"
                },
                "equipe": {
                    "description": "Relacionamento com o modelo Equipe",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Equipe"
                        }
                    ]
                },
                "funcao": {
                    "description": "Função do atleta",
                    "type": "string"
                },
                "id": {
                    "description": "ID do atleta",
                    "type": "integer"
                },
                "id_equipe": {
                    "description": "ID da equipe associada",
                    "type": "integer"
                },
                "idade": {
                    "description": "Idade do atleta",
                    "type": "integer"
                },
                "lider": {
                    "description": "Relacionamento com o modelo Lider",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Lider"
                        }
                    ]
                },
                "nome": {
                    "description": "Nome do atleta",
                    "type": "string"
                },
                "senha": {
                    "description": "Senha do atleta",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Data de atualização",
                    "type": "string"
                }
            }
        },
        "models.Equipe": {
            "description": "Representa uma equipe com informações básicas.",
            "type": "object",
            "properties": {
                "ativo": {
                    "description": "Status ativo da equipe",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "Data de criação",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Data de exclusão (opcional)",
                    "type": "string"
                },
                "id": {
                    "description": "ID da equipe",
                    "type": "integer"
                },
                "nome": {
                    "description": "Nome da equipe",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Data de atualização",
                    "type": "string"
                }
            }
        },
        "models.Lider": {
            "description": "Representa um líder com informações básicas.",
            "type": "object",
            "properties": {
                "cpf": {
                    "description": "CPF do líder",
                    "type": "string"
                },
                "createdAt": {
                    "description": "Data de criação",
                    "type": "string"
                },
                "deletedAt": {
                    "description": "Data de exclusão (opcional)",
                    "type": "string"
                },
                "email": {
                    "description": "Email do líder",
                    "type": "string"
                },
                "nome": {
                    "description": "Nome do líder",
                    "type": "string"
                },
                "senha": {
                    "description": "Senha do líder",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Data de atualização",
                    "type": "string"
                }
            }
        },
        "models.Pergunta": {
            "description": "Representa uma pergunta com um conjunto de respostas.",
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID da pergunta",
                    "type": "integer"
                },
                "pergunta": {
                    "description": "Texto da pergunta",
                    "type": "string"
                },
                "respostas": {
                    "description": "Respostas associadas",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Resposta"
                    }
                }
            }
        },
        "models.Resposta": {
            "description": "Representa uma resposta associada a uma pergunta.",
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID da resposta",
                    "type": "integer"
                },
                "pergunta_id": {
                    "description": "ID da pergunta associada",
                    "type": "integer"
                },
                "resposta": {
                    "description": "Texto da resposta",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
